<a href="https://colab.research.google.com/github/Ayat30/csv/blob/master/Random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from random import choice
from numpy import array, dot, random
 
step_fun = lambda x: 0 if x < 0 else 1
 
training_dataset = [
    (array([0,0,1]),0),
     (array([0,1,1]),1),
      (array([1,0,1]),1),
       (array([1,1,1]),1),]
 
w = random.rand(3) 
error = []
eta = 0.3
n = 100
for j in range(n):
  x,expected = choice(training_dataset)
  result = dot(w,x)
  err = expected - step_fun(result)
  error.append(err)
w += eta * err * x
for x,_ in training_dataset:
 result = dot(x,w)
print("{}: {} -> {}".format(x[:3], result, step_fun(result)))

[1 1 1]: 0.0933928643359449 -> 1
